# Generated by Django 4.2.7 on 2025-10-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='next_action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
